<?php
/**
 * Created by PhpStorm.
 * User: Ivany
 * Date: 13.05.2016
 * Time: 20:09
 */
namespace app\components;
 use yii\base\Widget;

 class CompanyWidget extends Widget{

     public function init()
     {
         parent::init(); // TODO: Change the autogenerated stub
     }

     public function run()
     {
         return $this->render('company');
     }
 }